---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
env:
  AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua-policy.yaml
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
permissions: {}
jobs:
  actionlint:
    # Lint GitHub Actions Workflows by actionlint.
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@0c06ab0fadfa4f27569001388515dafdabc11bb3 # v0.2.0
    permissions:
      pull-requests: write
      contents: read
