name: renovate

on: pull_request
permissions: {}
jobs:
  update-aqua-checksums-renovate:
    # Update aqua-checksums.json and push a commit
    runs-on: ubuntu-latest
    environment: renovate
    if: github.event.pull_request.user.login == 'renovate[bot]'
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
      - name: Install ghcp
        uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
        # Install ghcp
        with:
          aqua_version: v1.32.2
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - name: Update aqua-checksums.json
        uses: aquaproj/update-checksum-action@2413c534a7d2cd2ce7a0dfb5a686e5142e565ce3 # v0.1.3
        with:
          prune: true
        env:
          # To trigger GitHub Actions Workflow by pushing a commit, GitHub App token is required.
          # github.token doesn't trigger GitHub Actions Workflow.
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          # > When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - name: Enable auto-merge
        if: |
          contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
        run: gh -R "$GITHUB_REPOSITORY" pr merge --merge --auto --delete-branch "$PR_NUMBER"
        env:
          # github.token is unavailable, because github.token doesn't have a permission to delete a branch `renovate/*`
          # pull-requests: write and contents: write are required
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
          PR_NUMBER: ${{github.event.pull_request.number}}
      # https://github.com/cli/cli/issues/6680
      # HTTP 401: Personal access tokens with fine grained access do not support the GraphQL API (https://api.github.com/graphql)
      # - run: gh -R aquaproj/example-update-checksum pr review -a "$PR_NUMBER"
      - name: Approve a pull request
        if: |
          contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" \
            -f event='APPROVE'
        env:
          PR_NUMBER: ${{github.event.pull_request.number}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN_APPROVE_RENOVATE_PR}}
