---
name: test

on: pull_request

permissions: {}

jobs:
  path-filter:
    # Get changed files to filter jobs
    timeout-minutes: 30
    outputs:
      update-aqua-checksums: ${{steps.changes.outputs.update-aqua-checksums}}
      update-aqua-checksums-renovate: ${{steps.changes.outputs.update-aqua-checksums-renovate}}
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          filters: |
            update-aqua-checksums:
              - aqua.yaml
              - aqua/*.yaml
              - aqua-checksums.json
              - .github/workflows/test.yaml
              - .github/workflows/wc-update-aqua-checksums.yaml
            update-aqua-checksums-renovate:
              - aqua.yaml
              - aqua/*.yaml
              - aqua-checksums.json
              - .github/workflows/test.yaml
              - .github/workflows/wc-update-aqua-checksums-renovate.yaml
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/wc-renovate-config-validator.yaml
              - .github/workflows/test.yaml

  status-check:
    uses: ./.github/workflows/wc-status-check.yaml
    permissions: {}
    needs:
      - renovate-config-validator
      - update-aqua-checksums
      - update-aqua-checksums-renovate
      - test
    if: failure()

  enable-auto-merge-and-approve:
    uses: ./.github/workflows/wc-enable-auto-merge-and-approve.yaml
    needs:
      - status-check
    if: |
      ! failure() && ! cancelled() && github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    secrets:
      gh_token: ${{secrets.GH_TOKEN_APPROVE_RENOVATE_PR}}
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

  renovate-config-validator:
    uses: ./.github/workflows/wc-renovate-config-validator.yaml
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  update-aqua-checksums:
    needs: path-filter
    # Exclude pull requests from Renovate
    if: |
      needs.path-filter.outputs.update-aqua-checksums == 'true' && github.event.pull_request.user.login != 'renovate[bot]'
    uses: ./.github/workflows/wc-update-aqua-checksums.yaml
    permissions:
      contents: read
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

  update-aqua-checksums-renovate:
    needs: path-filter
    if: |
      needs.path-filter.outputs.update-aqua-checksums-renovate == 'true' && github.event.pull_request.user.login == 'renovate[bot]'
    uses: ./.github/workflows/wc-update-aqua-checksums-renovate.yaml
    permissions:
      contents: read
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

  test:
    uses: ./.github/workflows/wc-test.yaml
    permissions: {}
