---
name: test

on: pull_request

permissions: {}

jobs:
  path-filter:
    # Get changed files to filter jobs
    outputs:
      update-aqua-checksums: ${{steps.changes.outputs.update-aqua-checksums}}
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            update-aqua-checksums:
              - aqua.yaml
              - aqua/*.yaml
              - aqua-checksums.json
              - .github/workflows/test.yaml
            renovate-config-validator:
              - renovate.json5

  status-check:
    # This job is used for main branch's branch protection rule's status check.
    # If all dependent jobs succeed or are skipped this job succeeds.
    runs-on: ubuntu-latest
    needs:
      - approve-and-enable-automerge-renovate
      - update-aqua-checksums
      - test
      - renovate-config-validator
    permissions: {}
    if: failure()
    steps:
      - run: exit 1

  approve-and-enable-automerge-renovate:
    runs-on: ubuntu-latest
    environment: renovate
    if: |
      github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
      - name: Enable auto-merge
        run: gh -R "$GITHUB_REPOSITORY" pr merge --merge --auto --delete-branch "$PR_NUMBER"
        env:
          # github.token is unavailable, because github.token doesn't have a permission to delete a branch `renovate/*`
          # pull-requests: write and contents: write are required
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
          PR_NUMBER: ${{github.event.pull_request.number}}
      # https://github.com/cli/cli/issues/6680
      # HTTP 401: Personal access tokens with fine grained access do not support the GraphQL API (https://api.github.com/graphql)
      # - run: gh -R aquaproj/example-update-checksum pr review -a "$PR_NUMBER"
      - name: Approve a pull request
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            "/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews" \
            -f event='APPROVE'
        env:
          PR_NUMBER: ${{github.event.pull_request.number}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN_APPROVE_RENOVATE_PR}}

  update-aqua-checksums-renovate:
    # Update aqua-checksums.json and push a commit
    needs: path-filter
    runs-on: ubuntu-latest
    environment: renovate
    if: |
      needs.path-filter.outputs.update-aqua-checksums == 'true' && github.event.pull_request.user.login == 'renovate[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
      - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
        # Install ghcp
        with:
          aqua_version: v1.34.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: aquaproj/update-checksum-action@d5d72955a3da19ccf7b9ecb8080bc92247fd6633 # v0.2.1
        with:
          prune: true
        env:
          # To trigger GitHub Actions Workflow by pushing a commit, GitHub App token is required.
          # github.token doesn't trigger GitHub Actions Workflow.
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          # > When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

  update-aqua-checksums:
    # Update aqua-checksums.json and push a commit
    needs: path-filter
    # Exclude pull requests from Renovate
    if: |
      needs.path-filter.outputs.update-aqua-checksums == 'true' && github.event.pull_request.user.login != 'renovate[bot]'
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@c766f4606e9aedc9c5c864f7ee28aed25284a3cf # v0.1.4
    permissions:
      contents: read
    with:
      aqua_policy_config: aqua-policy.yaml
      aqua_version: v1.34.0
      prune: true
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

  test:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: echo test

  renovate-config-validator:
    # Validate Renovate Configuration by renovate-config-validator.
    uses: suzuki-shunsuke/renovate-config-validator-workflow/.github/workflows/validate.yaml@1a2fd7b15d99b1c434124b0bd2d8bd55b54ed869 # v0.2.0
    needs: path-filter
    if: ${{needs.path-filter.outputs.renovate-config-validator == 'true'}}
    permissions:
      contents: read
