name: test

on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  path-filter:
    outputs:
      update-aqua-checksums: ${{steps.changes.outputs.update-aqua-checksums}}
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      actionlint: ${{steps.changes.outputs.actionlint}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            update-aqua-checksums:
              - aqua.yaml
              - aqua/*.yaml
              - aqua-checksums.json
              - .github/workflows/test.yaml
            renovate-config-validator:
              - renovate.json5
            actionlint:
              - aqua/actionlint.yaml
              - aqua/reviewdog.yaml
              - .github/workflows/*.yaml

  update-aqua-checksums:
    runs-on: ubuntu-latest
    needs: path-filter
    permissions: {}
    if: |
      needs.path-filter.outputs.update-aqua-checksums == 'true' && github.event.pull_request.user.login != 'renovate[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      # https://aquaproj.github.io/docs/reference/checksum
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
      - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
        with:
          aqua_version: v1.32.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: aquaproj/update-checksum-action@5165a9262bcac3d7e676a137df943a34bcf31917 # v0.1.2
        with:
          prune: true
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

  test:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
        with:
          aqua_version: v1.32.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: tfcmt -v
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

  renovate-config-validator:
    uses: suzuki-shunsuke/renovate-config-validator-workflow/.github/workflows/validate.yaml@1a2fd7b15d99b1c434124b0bd2d8bd55b54ed869 # v0.2.0
    needs: path-filter
    if: ${{needs.path-filter.outputs.renovate-config-validator == 'true'}}
    permissions:
      contents: read

  actionlint:
    if: ${{needs.path-filter.outputs.actionlint == 'true'}}
    needs: path-filter
    permissions:
      pull-requests: write
      contents: read
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@0c06ab0fadfa4f27569001388515dafdabc11bb3 # v0.2.0

  status-check:
    runs-on: ubuntu-latest
    needs:
      - update-aqua-checksums
      - test
      - renovate-config-validator
      - actionlint
    permissions: {}
    if: failure()
    steps:
      - run: exit 1
