name: test

on:
  pull_request:
    branches: [main]
    paths:
      - aqua.yaml
      - aqua-checksums.json
      - .github/workflows/test.yaml

permissions:
  contents: write # required to push a commit to update aqua-checksums.json

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.2.0
        with:
          aqua_version: v1.26.2

      # https://aquaproj.github.io/docs/reference/checksum
      - uses: aquaproj/update-checksum-action@v0.1.0
        env:
          # To trigger GitHub Actions Workflow, you should use Personal Access Token or GitHub App token.
          GITHUB_TOKEN: ${{github.token}}
